/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyHikesRouteImport } from './routes/my-hikes'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as HikesIndexRouteImport } from './routes/hikes.index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as MessagesHikeIdRouteImport } from './routes/messages.$hikeId'
import { Route as HikesSlugRouteImport } from './routes/hikes.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHikesRoute = MyHikesRouteImport.update({
  id: '/my-hikes',
  path: '/my-hikes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const HikesIndexRoute = HikesIndexRouteImport.update({
  id: '/hikes/',
  path: '/hikes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesHikeIdRoute = MessagesHikeIdRouteImport.update({
  id: '/messages/$hikeId',
  path: '/messages/$hikeId',
  getParentRoute: () => rootRouteImport,
} as any)
const HikesSlugRoute = HikesSlugRouteImport.update({
  id: '/hikes/$slug',
  path: '/hikes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/my-hikes': typeof MyHikesRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/hikes/$slug': typeof HikesSlugRoute
  '/messages/$hikeId': typeof MessagesHikeIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/hikes/': typeof HikesIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/my-hikes': typeof MyHikesRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/hikes/$slug': typeof HikesSlugRoute
  '/messages/$hikeId': typeof MessagesHikeIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/hikes': typeof HikesIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/my-hikes': typeof MyHikesRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/hikes/$slug': typeof HikesSlugRoute
  '/messages/$hikeId': typeof MessagesHikeIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/hikes/': typeof HikesIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/login'
    | '/me'
    | '/my-hikes'
    | '/notifications'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/hikes/$slug'
    | '/messages/$hikeId'
    | '/profile/$id'
    | '/hikes/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/login'
    | '/me'
    | '/my-hikes'
    | '/notifications'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/hikes/$slug'
    | '/messages/$hikeId'
    | '/profile/$id'
    | '/hikes'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/login'
    | '/me'
    | '/my-hikes'
    | '/notifications'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/hikes/$slug'
    | '/messages/$hikeId'
    | '/profile/$id'
    | '/hikes/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  MyHikesRoute: typeof MyHikesRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  HikesSlugRoute: typeof HikesSlugRoute
  MessagesHikeIdRoute: typeof MessagesHikeIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  HikesIndexRoute: typeof HikesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hikes': {
      id: '/my-hikes'
      path: '/my-hikes'
      fullPath: '/my-hikes'
      preLoaderRoute: typeof MyHikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hikes/': {
      id: '/hikes/'
      path: '/hikes'
      fullPath: '/hikes/'
      preLoaderRoute: typeof HikesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$hikeId': {
      id: '/messages/$hikeId'
      path: '/messages/$hikeId'
      fullPath: '/messages/$hikeId'
      preLoaderRoute: typeof MessagesHikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hikes/$slug': {
      id: '/hikes/$slug'
      path: '/hikes/$slug'
      fullPath: '/hikes/$slug'
      preLoaderRoute: typeof HikesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  MyHikesRoute: MyHikesRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  HikesSlugRoute: HikesSlugRoute,
  MessagesHikeIdRoute: MessagesHikeIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  HikesIndexRoute: HikesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
